language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - cpanm ExtUtils::MakeMaker
  - cpanm ExtUtils::MakeMaker::CPANfile
  - cpanm -n git://github.com/kan/coveralls-perl.git
script: perl Makefile.PL && cover -test
after_success:
  - cover -report coveralls
notifications:
  email:
    - i.naoya+md2inao@gmail.com
  irc:
    - "irc.freenode.net#md2inao"
deploy:
  provider: heroku
  buildpack: "https://github.com/pnu/heroku-buildpack-perl/"
  app: md2inao
  api_key:
    secure: IbLmvicDRtQJwz5CqeEoQHIZfq+BJBgc6TIeLHFuxtJX0bqVoNxTX/0eQHUQfS4ZQypL7yFWK4t5z2q0FGLppGjZDdR2Iy+hz0AG/ND9hLp8wO8AwRpZfzDXLUwQg5FkIBTf9329s2wCgEUWu7GKum20g9BvLfboXPUNawJB6k8=
  on:
    perl: "5.18.2"
