language: perl
perl:
  - "5.16"
  - "5.14"
before_install:
  - cpanm Module::Install::Repository
  - cpanm Module::Install::ReadmeFromPod
  - cpanm Module::Install::CPANfile
  - cpanm Test::Base
script: "make test"
notifications:
  email:
    - i.naoya+md2inao@gmail.com
