language: perl
perl:
  - "5.16"
  - "5.14"
before_install:
  - cpanm Module::Install::Repository
  - cpanm Module::Install::ReadmeFromPod
  - cpanm Module::Install::CPANfile
notifications:
  email:
    - i.naoya+md2inao@gmail.com
  irc:
    - "irc.freenode.org#md2inao"
